audit_header: false
title: Bakersfield Real Estate Video Blog with Vince Link
description: Our mission at The Link Team is to be your best resource for Bakersfield real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The The Link Team, your professional Bakersfield Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Vince Link
  title:
  license_number:
  about_markdown: |
    With passion and commitment, Vince Link is taking the Kern County Real Estate market head-on. His commitment is to help every buyer own a piece of the American dream, and every seller to have a quick and smooth transaction. His passion fuels his love for Real Estate and for helping the community. Vince is a father, a husband, and a full-time, dedicated, and professional Realtor, who always makes the needs of his clients a top priority. Call Vince today!
  brand: The Link Team
  brokerage: Open Door Real Estate
  market: Bakersfield
  address: 5351 Olive Dr Bakersfield CA 93308
  phone: 661-321-6640
  phone_type:
  phone2:
  phone2_type:
  email: vincelinkteam@gmail.com
  url: http://www.linkteamhomes.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.linkteamhomes.com/home-valuation
  second_CTA_text: Home Search
  second_CTA_URL: https://search.linkteamhomes.com/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Bakersfield Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.linkteamhomes.com/home-valuation

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Bakersfield Home?"
    CTA_text2: "Search the entire MLS for your Bakersfield home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://search.linkteamhomes.com/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Bakersfield Real Estate Podcast with Vince Link'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Bakersfield Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from The Link Team - your professional Bakersfield Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Bakersfield, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Vince Link'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Bakersfield Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#0E8F7C'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#0E8F7C'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
